version: '3.7'

services:
  expo:
    build: .
    ports:
      - '19000:19000' # Port for React Native App
      - '19001:19001' # Port for React Native Debugging
    env_file: .env # Create a .env file in project root directory specifying REACT_NATIVE_PACKAGER_HOSTNAME=<local IP Address>
    volumes:
      - .:/app # Live Reload
      - /app/node_modules # Prevents node_modules being overwritten by host directory
    command: npm start
