name: Docker Compose CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose --file docker-compose.test.yml up -d

      - name: Test Ports
        run: docker run --network container:travel-hustle-app_django_1 appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8000

      - name: Test Expo Ports
        run: docker run --network container:travel-hustle-app_expo_1 appropriate/curl -s --retry 10 --retry-connrefused http://localhost:19000
