name: React Native CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install NPM Modules
        working-directory: ./frontend
        run: npm install

      - name: Run ESLint
        working-directory: ./frontend
        run: eslint --ext .js,.jsx,.ts,.tsx .

      - name: Run Jest Tests
        working-directory: ./frontend
        run: npm test
